### ISSUE TITLE
Allow for lisp initialization at library load-time

### ISSUE THREAD

**Issue by braised-babbage** [quil-lang/sbcl-librarian#5]
On most systems, specific code can be executed at shared library load time (as per [DllMain](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-entry-point-function) on Windows or `.init` for Linux/macOS). The use of this would free us from having to initialize manually, and would save us the risk of clients trying to initialize multiple times. On the other hand, to do this we may need a somewhat stricter policy for how the core file is distributed relative to the shared library.

**Comment by karlosz** [comment]
Yes, this sounds like a good idea. We'll have to watch out for portability: not just among platforms but among compilers/linkers too. The best way to do this seems to be a GCC specific attribute `__attribute__((constructor))`: This is useful for our case of calling `initialize_lisp` to get all the function pointers ready. If we can guarantee that shared libraries only get loaded once (and hence the constructors are called once), we have solved the multiple-user problem. Otherwise, it should just be a matter of having a static variable in the constructor function and checking that for `ran_once`.

What about finalization? We don't have a good story for this, and it seems like doing it on library unloading time makes sense but may make it harder to coordinate resources. This may not matter at all.

**Comment by kartik-s** [comment]
On an unrelated note, we can implement shared library initializers/finalizers portably across platforms **and** compilers using C++'s global static object constructors/destructors if we use a C++ compiler to build our shared libraries instead of a C compiler. The built libraries can still be linked against C programs so long as the exported symbols are wrapped in `extern "C"` as needed.

**Comment by kartik-s** [comment]
I removed :pauseless-threadstart with [this commit to SBCL](https://github.com/sbcl/sbcl/commit/96f0f2612ee69055ad956947cbea9932dd3bccc3), and now libsbcl_librarian initializes the Lisp runtime when it gets loaded into a process (see #65).
